### ISSUE TITLE
BUG : <Title>App Crash in Kotlin

### ISSUE THREAD

**Issue by Tilakrk21** [rudderlabs/rudder-sdk-android#375]
Hey,
I am getting the below crash. Can anyone please help

Fatal Exception: net.sqlcipher.database.SQLiteException: database is locked: UPDATE events SET status = (status | 2) WHERE id IN (121493,121494,121495,121496,121497);
       at net.sqlcipher.database.SQLiteDatabase.native_execSQL(SQLiteDatabase.java)
       at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2439)
       at com.rudderstack.android.sdk.core.DBPersistentManager.updateEventStatus(DBPersistentManager.java:572)
       at com.rudderstack.android.sdk.core.DBPersistentManager.markCloudModeDone(DBPersistentManager.java:562)
       at com.rudderstack.android.sdk.core.RudderCloudModeManager$1.run(RudderCloudModeManager.java:57)

**Comment by itsdebs** [comment]
@Tilakrk21 thanks for reporting. Which version of SDK are you using?

**Comment by itsdebs** [comment]
Can you please update to 1.21.1 and check if you are still facing this?

**Comment by Tilakrk21** [comment]
> Can you please update to 1.21.1 and check if you are still facing this?

Okay. I will check

**Comment by desusai7** [comment]
Hey @Tilakrk21, 

Have you tried updating to 1.21?

**Comment by 1abhishekpandey** [comment]
Hey @Tilakrk21,
I wanted to inform you that I'm closing this issue as it has been inactive for a significant period of time. While we haven't received any updates or responses regarding this issue, please know that you're always welcome to reopen it if you encounter the problem again or have any additional information to share. Your feedback is valuable to us, and we want to ensure that all issues are addressed promptly.

**Comment by prajjwal-epifi** [comment]
hey, @desusai7 @itsdebs,
We are still seeing the above crash even after upgrading to 1.21.3

**Comment by 1abhishekpandey** [comment]
Hey @prajjwal-epifi,
Can you please help us with the following information:
1. How often does this crash occur and what percentage of your customers are affected by it?
2. Does this happen on any specific device or Android version?

**Comment by prajjwal-epifi** [comment]
1. Although adoption of new build(after upgrading) is very low, we have experienced 110 crashes in the last 5 days.
2. These crashes are occurring across all devices and Android OS versions.

**Comment by 1abhishekpandey** [comment]
Hey @prajjwal-epifi,
Could you please confirm if you are using our database encryption feature? I believe this exception is related to that package. Once you confirm, we can suggest the next step.

**Comment by prajjwal-epifi** [comment]
yes, we are using a rudder DB encryption.
```
.withDbEncryption(
                    RudderConfig.DBEncryption(
                        true,
                        rudderEncryptedDbKey,
                        PersistenceProviderFactory::class.java.canonicalName
                    )
                )
```
In PersistenceProviderFactory, we are overriding DB name only.

**Comment by 1abhishekpandey** [comment]
As per our investigation, this issue is caused by the deprecated https://github.com/sqlcipher/android-database-sqlcipher dependency (as reported in your stack trace: at net.sqlcipher.database.SQLiteDatabase.native_execSQL(SQLiteDatabase.java)). We have already updated to the latest version of this dependency: https://github.com/sqlcipher/sqlcipher-android.

We request you to upgrade to the latest version of our SDK [v1.23.2](https://github.com/rudderlabs/rudder-sdk-android/releases/tag/v1.23.2) and also update the following SQLCipher dependencies:

```
implementation "net.zetetic:sqlcipher-android:4.5.6@aar"
implementation "androidx.sqlite:sqlite:2.3.1"
```

You can refer to our DbEncryption documentation if required: https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-android-sdk/#dbencryption.

If the issue persists, please create a new issue. For now, we are closing this one.
